### ISSUE TITLE
Register Submodel at DTR

### ISSUE THREAD

**Issue by f-zimmer** [eclipse-tractusx/puris#183]
**As** Catena Adopter,
**I want** to register submodels in my digital Twin Registry,
**so that** I my partners can find the submodel for item stock.

## Hints / Details

- Register Submodel at DTR means that one needs to register or update the Submodel Descriptor. 
  - As a supplier I have one twin for multiple customers
  - As a customer I have one twin per supplier
  - Note: Same as for edc asset registration, the registry should be created. It's likely that it relies on the material partner relationship and we need to change the datamodel as proposed for #180 . 
  - Note 2: Example for supplier side registration is noted in standardization candidate document. Get in touch with @tom-rm-meyer-ISST for introduction
- Folloc concept created in #179 
- For submodel register asset created in edc within #181 

### Outcome
- ...
### Acceptance Criteria
- Registration of Submodels at DDTR has been refactored (enhance parametrization)

## Out of Scope

- Other submodels than item stock

**Comment by tom-rm-meyer-ISST** [comment]
PR #308
