### ISSUE TITLE
Migrate Tractus EDC to 0.6.x

### ISSUE THREAD

**Issue by f-zimmer** [eclipse-tractusx/puris#184]
**As** a puris adopter,
**I want** to use the latest version of the edc,
**so that** I'm conform to the platform.

## Hints / Details

- 

### Outcome
- ...
### Acceptance Criteria
- Local Deployment has been updated
- INT deployments have been updated
- Code changes - if needed - have been done

## Out of Scope

- ...

**Comment by tom-rm-meyer-ISST** [comment]
Update of EDC has a problem with proxyMethod. I asked in the EDC Chatgroup: https://matrix.to/#/!mYxOilDPMLCQhMoIVc:matrix.eclipse.org/$umGUGgudYbvGIQSeETJgJXN9RBxgZ9wo3lMgZc5k5yY?via=matrix.eclipse.org&via=matrix.org&via=dev-null.rocks
