### ISSUE TITLE
[TRG 1.04] Diagrams as code 

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/puris#261]
There is a number of diagrams in  docs/userGuide/img stored as .png files. 
Please consider ahering to [TRG 1.04](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4/), describing the process of creation and modification / change to other suggested methods.

Updates https://github.com/eclipse-tractusx/puris/issues/257

**Comment by tom-rm-meyer-ISST** [comment]
I propose to reject this one. The png files are screenshots of the application for better readability. For diagrams (e.g. docs/arc42/05_building_block_view.md) we're using a subfolder containing the puml files and the generated images.
