### ISSUE TITLE
QG checks (Release 24.05)

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/puris#363]
## QG checks
Please keep this issue open until QG is concluded and will be managed by the Issue Creator!
We will inform you about finding and proposals in separated issues, this issue here is for the Overview of the Checks!

### Please keep this issue open until QG is concluded!

Product Owner:   
Dev SPOC: @tom-rm-meyer-ISST  
Helm Chart Version: tbd 
App Version: 2.0.0

Release Managemnet Reference Issue: eclipse-tractusx/sig-release#589

### Check of Tractus-X Release Guidelines

- Currently implemented automatic checks can be found under your product on our [Release Guidelines Checks Board](https://eclipse-tractusx.github.io/sig-release/) 
- This QG Check is depending on the mandatory information from our current [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)

#### TRG 1 Documentation

- [x] [TRG 1.01](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1) appropriate `README.md` 
- [x] #385
- [x] [TRG 1.03](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3) appropriate `CHANGELOG.md`
- [x] [TRG 1.04](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4) editable static files

#### TRG 2 Git

- [x] [TRG 2.01](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1) default branch is named `main`
- [x] [TRG 2.03](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3) repository structure
- [x] [TRG 2.04](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4) leading product repository
- [x] [TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5) `.tractusx` metafile in a proper format

#### TRG 3 Kubernetes

- [x] [TRG 3.02](https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2) persistent volume and persistent volume claim is used when needed

#### TRG 4 Container

- [x] [TRG 4.01](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-01) [semantic versioning](https://semver.org/) and tagging 
- [x] [TRG 4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02) base image is agreed  
- [x] [TRG 4.03](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-03) image has `USER` command and Non Root Container
- [x] [TRG 4.05](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05) released image must be placed in `DockerHub`, remove `GHCR` references 
- [x] #386

#### TRG 5 Helm

- [x] #387
- [x] [TRG 5.02](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02) Helm chart location in `/charts` directory and correct structure
- [x] [TRG 5.03](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-03) proper version strategy 
- [x] [TRG 5.04](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04) CPU / MEM resource requests and limits and are properly set
- [x] [TRG 5.06](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06) Application must be configurable through the Helm chart 
- [x] [TRG 5.07](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07) Dependencies are present and properly configured in the Chart.yaml
- [x] [TRG 5.08](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08) Product has a single deployable helm chart that contains all components 
- [x] [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09) Helm Test running properly
- [x] [TRG 5.10](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-10) Products need to support 3 versions at a time
- [x] [TRG 5.11](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11) Upgradeability
 
#### TRG 6 Released Helm Chart

- [x] [TRG 6.01](https://eclipse-tractusx.github.io/docs/release/trg-6/trg-6-1) Released Helm Chart 

#### TRG 7 Open Source Governance
- [x] [TRG 7.01](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01) Legal Documentation
- [x] [TRG 7.02](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) License and copyright header  
- [x] [TRG 7.03](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03) IP checks for project content 
- [x] [TRG 7.04](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04) IP checks for 3rd party content
- [x] #388
- [x] [TRG 7.06](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06) Legal information for end user content
- [x] [TRG 7.07](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07) Legal notice for documentation
- [x] [TRG 7.08](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-08) Legal notice for KIT documentation

#### TRG 8 Security
- [x] [TRG 8.01](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-01) Mitigate high and above findings in CodeQL
- [x] [TRG 8.02](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-02) Mitigate high and above findings in KICS
- [x] [TRG 8.03](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03) Mitigate high and above findings in GitGuardian
- [x] [TRG 8.04](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-04) Mitigate high and above findings in Trivy

#### Information Sharing

**Comment by tom-rm-meyer-ISST** [comment]
@evegufy please start with the review :)

**Comment by tom-rm-meyer-ISST** [comment]
@RoKrish14 could you please check the Security issues?

**Comment by evegufy** [comment]
Hi @tom-rm-meyer-ISST as discussed, I created issues we discussed that it should be still added for the release, with the exception of `TRG 7.06 Legal information for end user content`, which is still WIP.

In the following some general recommadations:
Futher recommandation

	- Readme --> Remove Catena-X

	- Changelog --> remove dead links
https://github.com/eclipse-tractusx/puris/blob/2.0.0/CHANGELOG.md
https://github.com/eclipse-tractusx/puris/releases/tag/v2.0.0


	- Only create secret if not .Values.existingSecret
https://github.com/eclipse-tractusx/puris/blob/2.0.0/charts/puris/templates/backend-secrets.yaml
https://github.com/eclipse-tractusx/puris/blob/2.0.0/charts/puris/values.yaml#L362

https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/v1.0.0-rc.4/charts/ssi-credential-issuer/templates/secret.yaml
https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/v1.0.0-rc.4/charts/ssi-credential-issuer/values.yaml#L161


	- Build images for arm64
https://hub.docker.com/r/tractusx/app-puris-frontend/tags
https://hub.docker.com/r/tractusx/app-puris-backend/tags
See https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/755/files
Why: local sandbox

-Add contribution details (information about how to fork, etc) https://github.com/eclipse-tractusx/puris/blob/2.0.0/CONTRIBUTING.md

**Comment by tom-rm-meyer-ISST** [comment]
Hey @evegufy with #405 we finally fixed the legal stuff in 7.05. Could you please confirm the successfull release checks?

**Comment by evegufy** [comment]
QG review completed
