### ISSUE TITLE
Add Missing Readme.md & README.md.gotmpl content 

### ISSUE THREAD

**Issue by PaMarzec** [eclipse-tractusx/puris#56]
## Description
Due to a large code difference in #44 compared to main (over 1000 lines code), the changes in **puris/charts/puris/README.md** & **puris/charts/puris/charts/backendREADME.md.gotmpl** got deleted.
## Solution
Put changes in another PR.

**Comment by tom-rm-meyer-ISST** [comment]
solved by #60
