### ISSUE TITLE
feat: Connecting the backend baseUrl of frontend and backend in helm

### ISSUE THREAD

**Issue by PaMarzec** [eclipse-tractusx/puris#87]
## Description
Problem was firstly mentioned in #81 in the comment [here](https://github.com/eclipse-tractusx/puris/pull/81#discussion_r1390975727).
## Explanation
Because we had changed our EDC Controlplane host IP in the past, we didn't realise that it also had to be adjusted in the frontend.
It would therefore be more practical for the frontend to automatically receive the IP from the backend so that it only needs to be configured in one place.

**Comment by tom-rm-meyer-ISST** [comment]
Within explanation, do you consider it to be a programmatic change or a configuration change ("frontend to automatically receive the IP from the backend")?
